# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e2220bb1ab95b3fff4d3b90c26876e2c"
name = "Dynamic price app"
handle = "dpa"
application_url = "https://bond-webcast-fiction-deutsche.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "niko-wonderwork.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,read_orders,read_product_listings,read_products,read_script_tags,read_themes,write_discounts,write_pixels,write_product_listings,write_products,write_script_tags,write_themes"

[auth]
redirect_urls = [
  "https://bond-webcast-fiction-deutsche.trycloudflare.com/auth/callback",
  "https://bond-webcast-fiction-deutsche.trycloudflare.com/auth/shopify/callback",
  "https://bond-webcast-fiction-deutsche.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
